"""Settings. One object, read from the environment, passed explicitly to every factory.

Nothing here holds a secret value in the repo: the dev defaults are dev-only credentials for the
container in ``docker-compose.yml``, and the production values arrive as environment variables.
See ``backend/.env.example`` for the full list.
"""

from __future__ import annotations

import json
from datetime import datetime, timedelta
from functools import lru_cache
from pathlib import Path
from typing import Any, Literal

from pydantic import Field, field_validator
from pydantic_settings import BaseSettings, SettingsConfigDict

BlobBackend = Literal["fs", "s3"]
SealKeyBackend = Literal["local", "aws_kms"]
SealProfileName = Literal["PAdES-B-T", "PAdES-B-LT", "PAdES-B-LTA"]
ObjectLockMode = Literal["COMPLIANCE", "GOVERNANCE"]

#: Retention floor for anything the service stores, in years. Overridable per document type.
DEFAULT_RETENTION_YEARS = 10

_REPO_BACKEND_DIR = Path(__file__).resolve().parents[2]


def _split_csv(value: Any) -> Any:
    """Accept either JSON (``["a","b"]``) or a plain comma-separated env var (``a,b``)."""
    if isinstance(value, str):
        text = value.strip()
        if not text:
            return []
        if text.startswith("["):
            return json.loads(text)
        return [part.strip() for part in text.split(",") if part.strip()]
    return value


class Settings(BaseSettings):
    model_config = SettingsConfigDict(
        env_file=".env",
        env_file_encoding="utf-8",
        extra="ignore",
        case_sensitive=False,
    )

    # ----------------------------------------------------------------- environment
    app_env: Literal["dev", "test", "prod"] = "dev"
    log_level: str = "INFO"

    # ----------------------------------------------------------------- database
    #: Runtime role: SELECT/INSERT on the append-only tables, DML on the rest, no DDL.
    database_url: str = "postgresql+psycopg://esign_app:esign_app_dev@localhost:54329/esign"
    #: Migration role. Owns every object; only `esign migrate` and the test harness use it.
    database_owner_url: str = "postgresql+psycopg://esign_owner:esign_owner_dev@localhost:54329/esign"
    #: Where `python -m esign.migrate` looks for numbered SQL files.
    migrations_dir: Path = _REPO_BACKEND_DIR / "migrations"
    db_echo: bool = False
    db_pool_size: int = 5

    # ----------------------------------------------------------------- blob store
    blob_backend: BlobBackend = "fs"
    #: fs backend: root directory for content-addressed, write-once files.
    blob_fs_root: Path = _REPO_BACKEND_DIR.parent / ".blobstore"
    #: s3 backend.
    blob_s3_bucket: str = ""
    blob_s3_region: str = "us-east-1"
    blob_s3_endpoint_url: str | None = None
    blob_s3_prefix: str = "esign/"
    blob_s3_object_lock_mode: ObjectLockMode = "COMPLIANCE"
    blob_s3_sse: str = "AES256"
    blob_s3_sse_kms_key_id: str | None = None

    # ----------------------------------------------------------------- sealing
    seal_key_backend: SealKeyBackend = "local"
    #: SPEC section 5: ``PAdES-B-T`` is a deliberate dev/test choice, never a default anything
    #: could fall back to. ``.env.example`` and ``tests/conftest.py`` set it explicitly.
    seal_profile: SealProfileName = "PAdES-B-LT"
    #: local backend: the dev PKI generated by `esign dev-pki`. Never committed.
    dev_pki_dir: Path = _REPO_BACKEND_DIR.parent / ".dev-pki"
    #: aws_kms backend: the key that signs, plus the PEM chain that describes it.
    seal_kms_key_id: str = ""
    seal_kms_region: str = "us-east-1"
    seal_kms_endpoint_url: str | None = None
    seal_cert_path: Path | None = None
    seal_chain_path: Path | None = None
    #: RFC 3161 timestamp authority. Empty in unit tests, where an in-process dummy stands in.
    tsa_url: str = ""
    tsa_timeout_seconds: float = 10.0
    #: PEM bundle of the roots `Sealer.validate` is allowed to trust. Embedded certs never count.
    trust_roots_path: Path = _REPO_BACKEND_DIR.parent / ".dev-pki" / "trust-roots.pem"

    # ----------------------------------------------------------------- identity
    session_ttl_seconds: int = 1800
    auth_max_age_seconds: int = 43200  # 12 hours
    reauth_max_age_seconds: int = 120
    #: Addendum 1 C. How long, after its ``auth_time``, a re-authentication attestation for a user
    #: also covers that user's *other* sessions on the same host. ``0`` (the default) means it
    #: never does: an attestation covers the one session it was made for, which is one document.
    #: Capped at 900 seconds by validation, and still subordinate to ``reauth_max_age_seconds``
    #: (an attestation older than that covers nothing, span or no span).
    reauth_span_seconds: int = Field(default=0, ge=0, le=900)
    #: Proxies whose X-Forwarded-For may be believed. Everything else uses the peer address.
    trusted_proxy_cidrs: tuple[str, ...] = ()
    default_locale: str = "en-US"

    # ----------------------------------------------------------------- envelopes
    approved_document_types: tuple[str, ...] = (
        "patient_consent",
        "hipaa_acknowledgement",
        "procedure_consent",
        "clinical_order",
    )
    #: Years to retain the sealed document, per document type. Anything absent gets the default.
    retention_years_by_document_type: dict[str, int] = Field(default_factory=dict)
    default_retention_years: int = DEFAULT_RETENTION_YEARS
    envelope_default_ttl_days: int = 14

    # ----------------------------------------------------------------- limits
    max_template_bytes: int = 20 * 1024 * 1024
    max_template_pages: int = 50
    #: Addendum 1 A. A scan of a paper-signed document (``POST /v1/archives``) is inspected under
    #: the template hygiene rules with these bounds instead of the template ones: image-only pages
    #: are larger than rendered text, and a long consent packet has more of them. The archive
    #: route admits a body up to ``max_scan_bytes`` plus multipart overhead, not ``max_request_bytes``.
    max_scan_bytes: int = 20 * 1024 * 1024
    max_scan_pages: int = 100
    max_signature_png_bytes: int = 1024 * 1024
    max_signature_png_pixels: int = 4_000_000
    #: Per-axis bounds. A 4000x1 image passes the byte and pixel limits and is not a signature,
    #: and a per-axis bound is the cheapest guard against a header-declared bomb.
    max_signature_png_dimension: int = 4000
    min_signature_png_dimension: int = 8
    #: The two client-supplied strings that are stamped into the document and kept for years: a
    #: typed signature and a text field's value. One definition, read by the API body and by the
    #: envelope service (which the worker, the CLI and the tests also drive).
    max_typed_signature_chars: int = 200
    max_text_field_chars: int = 2000
    max_request_bytes: int = 8 * 1024 * 1024

    # ----------------------------------------------------------------- api and worker
    #: The built signing UI (``bun run build``). Served at /sign when the directory exists.
    frontend_dist_dir: Path = _REPO_BACKEND_DIR.parent / "frontend" / "dist"
    #: Hosts' ``templates/`` directory for ``esign templates import``.
    templates_dir: Path = _REPO_BACKEND_DIR.parent / "templates"
    worker_poll_seconds: float = 5.0
    #: A seal job claimed longer ago than this is assumed abandoned by a dead worker.
    seal_job_lock_timeout_seconds: int = 600
    webhook_timeout_seconds: float = 10.0
    webhook_max_attempts: int = 12
    #: Idempotency keys are kept this long; a replay after that is treated as a new request.
    idempotency_ttl_hours: int = 48

    # ----------------------------------------------------------------- validators
    @field_validator("trusted_proxy_cidrs", "approved_document_types", mode="before")
    @classmethod
    def _csv_tuple(cls, value: Any) -> Any:
        return _split_csv(value)

    @field_validator("retention_years_by_document_type", mode="before")
    @classmethod
    def _json_dict(cls, value: Any) -> Any:
        if isinstance(value, str):
            text = value.strip()
            return json.loads(text) if text else {}
        return value

    # ----------------------------------------------------------------- helpers
    def retention_years(self, document_type: str) -> int:
        """Years a sealed document of this type must survive."""
        return self.retention_years_by_document_type.get(document_type, self.default_retention_years)

    def retain_until(self, document_type: str, now: datetime) -> datetime:
        """Absolute retain-until for the blob store. 365-day years: retention is a floor."""
        return now + timedelta(days=365 * self.retention_years(document_type))

    def default_expiry(self, now: datetime) -> datetime:
        return now + timedelta(days=self.envelope_default_ttl_days)

    def is_approved_document_type(self, document_type: str) -> bool:
        return document_type in self.approved_document_types


@lru_cache(maxsize=1)
def get_settings() -> Settings:
    """Process-wide settings. Tests build ``Settings(...)`` directly instead of calling this."""
    return Settings()
