-- Core schema. Owned by the architecture (docs/SPEC.md); modules do not edit this file.
-- A module that needs a schema change adds a new numbered migration in its own range
-- (see SPEC "Migrations") and says so in its report.

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- ---------------------------------------------------------------- hosts
-- A host is an EHR deployment that calls the server-to-server API.
CREATE TABLE hosts (
  id              uuid PRIMARY KEY,
  name            text NOT NULL,
  api_key_hash    bytea NOT NULL UNIQUE,          -- sha256 of the bearer key; the key itself is never stored
  allowed_origins text[] NOT NULL DEFAULT '{}',   -- origins allowed to embed the signing UI
  webhook_url     text,
  webhook_secret  bytea,
  created_at      timestamptz NOT NULL DEFAULT now(),
  disabled_at     timestamptz
);

-- ---------------------------------------------------------------- blobs
-- Content-addressed, write-once. Rows are never updated or deleted by the app role.
CREATE TABLE blobs (
  sha256       bytea PRIMARY KEY CHECK (octet_length(sha256) = 32),
  size_bytes   bigint NOT NULL CHECK (size_bytes >= 0),
  kind         text NOT NULL CHECK (kind IN
                 ('template_pdf','presented_pdf','revision_pdf','final_unsealed_pdf',
                  'sealed_pdf','signature_image')),
  storage_key  text NOT NULL,
  retain_until timestamptz,
  created_at   timestamptz NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------- templates
CREATE TABLE templates (
  id            uuid PRIMARY KEY,
  host_id       uuid NOT NULL REFERENCES hosts(id),
  key           text NOT NULL,
  name          text NOT NULL,
  document_type text NOT NULL,                    -- must be on the approved list (config)
  created_at    timestamptz NOT NULL DEFAULT now(),
  UNIQUE (host_id, key)
);

CREATE TABLE template_versions (
  id             uuid PRIMARY KEY,
  template_id    uuid NOT NULL REFERENCES templates(id),
  version        integer NOT NULL CHECK (version >= 1),
  status         text NOT NULL CHECK (status IN ('draft','published','retired')),
  pdf_sha256     bytea NOT NULL REFERENCES blobs(sha256),
  fields         jsonb NOT NULL,                  -- list[FieldDef]
  prefill_fields jsonb NOT NULL DEFAULT '[]',     -- list[PrefillFieldDef]
  signer_roles   jsonb NOT NULL,                  -- list[SignerRoleDef]
  created_at     timestamptz NOT NULL DEFAULT now(),
  published_at   timestamptz,
  UNIQUE (template_id, version)
);

-- A published version is immutable: the only permitted change is published -> retired.
CREATE FUNCTION template_versions_guard() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF TG_OP = 'DELETE' THEN
    IF OLD.status <> 'draft' THEN
      RAISE EXCEPTION 'template version % is % and cannot be deleted', OLD.id, OLD.status;
    END IF;
    RETURN OLD;
  END IF;
  IF OLD.status = 'draft' THEN
    RETURN NEW;
  END IF;
  IF OLD.status = 'published' AND NEW.status = 'retired'
     AND (to_jsonb(NEW) - 'status') = (to_jsonb(OLD) - 'status') THEN
    RETURN NEW;
  END IF;
  RAISE EXCEPTION 'template version % is % and immutable', OLD.id, OLD.status;
END $$;
CREATE TRIGGER template_versions_guard BEFORE UPDATE OR DELETE ON template_versions
  FOR EACH ROW EXECUTE FUNCTION template_versions_guard();

-- ---------------------------------------------------------------- consent texts
CREATE TABLE consent_texts (
  id           uuid PRIMARY KEY,
  version      text NOT NULL,
  locale       text NOT NULL,
  body         text NOT NULL,
  body_sha256  bytea NOT NULL,
  effective_at timestamptz NOT NULL,
  UNIQUE (version, locale)
);

-- ---------------------------------------------------------------- envelopes
-- One envelope = one document going through the signing pipeline.
CREATE TABLE envelopes (
  id                      uuid PRIMARY KEY,
  host_id                 uuid NOT NULL REFERENCES hosts(id),
  template_version_id     uuid NOT NULL REFERENCES template_versions(id),
  document_type           text NOT NULL,
  patient_ref             text NOT NULL,          -- opaque host identifier, never a name or MRN
  host_document_ref       text,
  signing_order           text NOT NULL CHECK (signing_order IN ('sequential','parallel')),
  status                  text NOT NULL CHECK (status IN
                            ('created','in_progress','completed_pending_seal','sealed',
                             'declined','voided','expired')),
  presented_sha256        bytea REFERENCES blobs(sha256),   -- revision 1
  current_revision_sha256 bytea REFERENCES blobs(sha256),
  sealed_sha256           bytea REFERENCES blobs(sha256),
  supersedes_envelope_id  uuid REFERENCES envelopes(id),
  expires_at              timestamptz NOT NULL,
  created_at              timestamptz NOT NULL DEFAULT now(),
  completed_at            timestamptz,
  sealed_at               timestamptz,
  voided_at               timestamptz,
  void_reason_code        text
);
CREATE INDEX envelopes_host_status ON envelopes (host_id, status);
CREATE INDEX envelopes_expiry ON envelopes (expires_at) WHERE status IN ('created','in_progress');

CREATE TABLE signers (
  id                 uuid PRIMARY KEY,
  envelope_id        uuid NOT NULL REFERENCES envelopes(id),
  role_key           text NOT NULL,               -- matches SignerRoleDef.key
  host_user_id       text NOT NULL,
  display_name       text NOT NULL,               -- PHI: DB and PDF only, never logs or audit data
  capacity           text NOT NULL CHECK (capacity IN
                       ('self','guardian','proxy','witness','interpreter','clinician')),
  on_behalf_of       text,                        -- patient_ref when capacity is guardian/proxy
  order_index        integer NOT NULL,
  requires_reauth    boolean NOT NULL,
  status             text NOT NULL CHECK (status IN ('pending','viewed','consented','signed','declined')),
  consent_text_id    uuid REFERENCES consent_texts(id),
  viewed_at          timestamptz,
  consented_at       timestamptz,
  signed_at          timestamptz,
  declined_at        timestamptz,
  decline_reason_code text,
  UNIQUE (envelope_id, role_key),
  CHECK ((capacity IN ('guardian','proxy')) = (on_behalf_of IS NOT NULL))
);

CREATE TABLE document_revisions (
  id          uuid PRIMARY KEY,
  envelope_id uuid NOT NULL REFERENCES envelopes(id),
  revision_no integer NOT NULL CHECK (revision_no >= 1),
  kind        text NOT NULL CHECK (kind IN ('presented','signer_applied','final_unsealed','sealed')),
  sha256      bytea NOT NULL REFERENCES blobs(sha256),
  signer_id   uuid REFERENCES signers(id),
  created_at  timestamptz NOT NULL DEFAULT now(),
  UNIQUE (envelope_id, revision_no)
);

-- ---------------------------------------------------------------- sessions and re-authentication
CREATE TABLE signing_sessions (
  id                    uuid PRIMARY KEY,
  signer_id             uuid NOT NULL REFERENCES signers(id),
  token_hash            bytea NOT NULL UNIQUE,    -- sha256 of the opaque token
  auth_method           text NOT NULL,
  auth_time             timestamptz NOT NULL,
  kiosk_staff_user_id   text,
  kiosk_identity_check  text,
  ip                    inet,
  user_agent            text,
  presented_sha256      bytea REFERENCES blobs(sha256),  -- what this session was actually shown
  created_at            timestamptz NOT NULL DEFAULT now(),
  expires_at            timestamptz NOT NULL,
  revoked_at            timestamptz,
  CHECK ((kiosk_staff_user_id IS NULL) = (kiosk_identity_check IS NULL))
);
CREATE INDEX signing_sessions_signer ON signing_sessions (signer_id);

CREATE TABLE reauth_attestations (
  id          uuid PRIMARY KEY,
  session_id  uuid NOT NULL REFERENCES signing_sessions(id),
  method      text NOT NULL,
  auth_time   timestamptz NOT NULL,
  attested_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE signature_captures (
  id           uuid PRIMARY KEY,
  signer_id    uuid NOT NULL REFERENCES signers(id),
  field_id     text NOT NULL,
  kind         text NOT NULL CHECK (kind IN ('drawn','typed','click')),
  image_sha256 bytea REFERENCES blobs(sha256),
  typed_text   text,
  created_at   timestamptz NOT NULL DEFAULT now(),
  UNIQUE (signer_id, field_id),
  CHECK ((kind = 'drawn') = (image_sha256 IS NOT NULL)),
  CHECK ((kind = 'typed') = (typed_text IS NOT NULL))
);

-- ---------------------------------------------------------------- audit trail
-- Append-only, hash-chained per stream. See SPEC "Audit trail" for the canonical hash input.
CREATE TABLE audit_events (
  id              uuid PRIMARY KEY,
  stream_type     text NOT NULL CHECK (stream_type IN ('envelope','template','system')),
  stream_id       uuid NOT NULL,
  sequence        integer NOT NULL CHECK (sequence >= 1),
  event_type      text NOT NULL,
  actor_user_id   text,
  actor_role      text,
  actor_capacity  text,
  on_behalf_of    text,
  auth_method     text,
  session_id      uuid,
  ip              inet,
  user_agent      text,
  document_sha256 bytea,
  data            jsonb NOT NULL DEFAULT '{}',
  occurred_at     timestamptz NOT NULL,
  prev_event_hash bytea NOT NULL CHECK (octet_length(prev_event_hash) = 32),
  event_hash      bytea NOT NULL CHECK (octet_length(event_hash) = 32),
  UNIQUE (stream_type, stream_id, sequence)
);

CREATE FUNCTION forbid_mutation() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  RAISE EXCEPTION '% on % is forbidden: table is append-only', TG_OP, TG_TABLE_NAME;
END $$;

CREATE TRIGGER audit_events_no_update BEFORE UPDATE OR DELETE ON audit_events
  FOR EACH ROW EXECUTE FUNCTION forbid_mutation();
CREATE TRIGGER audit_events_no_truncate BEFORE TRUNCATE ON audit_events
  FOR EACH STATEMENT EXECUTE FUNCTION forbid_mutation();

CREATE TRIGGER blobs_no_update BEFORE UPDATE OR DELETE ON blobs
  FOR EACH ROW EXECUTE FUNCTION forbid_mutation();
CREATE TRIGGER document_revisions_no_update BEFORE UPDATE OR DELETE ON document_revisions
  FOR EACH ROW EXECUTE FUNCTION forbid_mutation();
CREATE TRIGGER consent_texts_no_update BEFORE UPDATE OR DELETE ON consent_texts
  FOR EACH ROW EXECUTE FUNCTION forbid_mutation();
CREATE TRIGGER reauth_attestations_no_update BEFORE UPDATE OR DELETE ON reauth_attestations
  FOR EACH ROW EXECUTE FUNCTION forbid_mutation();

-- ---------------------------------------------------------------- operational tables
CREATE TABLE idempotency_keys (
  scope           text NOT NULL,                  -- 'session:<uuid>' or 'host:<uuid>'
  key             text NOT NULL,
  request_hash    bytea NOT NULL,
  response_status integer,
  response_body   jsonb,
  created_at      timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (scope, key)
);

CREATE TABLE seal_jobs (
  envelope_id     uuid PRIMARY KEY REFERENCES envelopes(id),
  attempts        integer NOT NULL DEFAULT 0,
  next_attempt_at timestamptz NOT NULL DEFAULT now(),
  last_error_code text,
  locked_at       timestamptz,
  completed_at    timestamptz
);

CREATE TABLE webhook_deliveries (
  id              uuid PRIMARY KEY,
  host_id         uuid NOT NULL REFERENCES hosts(id),
  envelope_id     uuid NOT NULL REFERENCES envelopes(id),
  event           text NOT NULL,
  payload         jsonb NOT NULL,                 -- ids, statuses, hashes only
  attempts        integer NOT NULL DEFAULT 0,
  next_attempt_at timestamptz NOT NULL DEFAULT now(),
  delivered_at    timestamptz,
  last_status     integer
);
