-- 0700: Addendum 1 (docs/SPEC-ADDENDUM-1.md). Owned by the architecture, like 0001: everything
-- under each feature's "Model" heading, made once so the three features can be built in parallel
-- against a fixed schema. Module authors do not edit this file.
--
--   A. paper archives:        envelopes.kind and the attestation columns; scan blob and revision kinds
--   B. adopted signatures:    the adopted_signatures table; signature_captures.kind = 'adopted'
--   C. re-authentication span: reauth_attestations.host_id / host_user_id
--
-- Conventions follow 0001 and the later migrations: CHECKs tie a kind to the columns that only
-- make sense for it, partial unique indexes state the "at most one" rules, evidence tables get the
-- grant *and* the trigger, and nothing here touches an existing row.

-- ================================================================ A. paper archives

-- A paper archive is an envelope with no template, no signers and no sessions: one scan, one
-- attestation, straight to completed_pending_seal, then sealed like any other envelope.
ALTER TABLE envelopes
  ADD COLUMN kind text NOT NULL DEFAULT 'electronic'
    CONSTRAINT envelopes_kind_check CHECK (kind IN ('electronic', 'paper_archive')),
  ADD COLUMN paper_signed_on date,
  ADD COLUMN attestation jsonb,               -- Attestation: staff ids and names, statement, disposition, paper signers
  ADD COLUMN attested_at timestamptz;

-- Only an electronic envelope has a template or a signing order.
ALTER TABLE envelopes ALTER COLUMN template_version_id DROP NOT NULL;
ALTER TABLE envelopes ALTER COLUMN signing_order DROP NOT NULL;
ALTER TABLE envelopes
  ADD CONSTRAINT envelopes_kind_template CHECK ((kind = 'electronic') = (template_version_id IS NOT NULL)),
  ADD CONSTRAINT envelopes_kind_signing_order CHECK ((kind = 'electronic') = (signing_order IS NOT NULL)),
  -- Only a paper archive carries the paper facts, and it carries all of them.
  ADD CONSTRAINT envelopes_kind_paper CHECK (
    (kind = 'paper_archive') = (paper_signed_on IS NOT NULL)
    AND (kind = 'paper_archive') = (attestation IS NOT NULL)
    AND (kind = 'paper_archive') = (attested_at IS NOT NULL)
  ),
  -- The attestation's shape: an object with exactly these keys, the closed statement and
  -- disposition vocabularies, and paper_signers as a non-empty array. The names inside are PHI:
  -- database and PDF only, never audit data (archive.attested records a count).
  ADD CONSTRAINT envelopes_attestation_shape CHECK (
    attestation IS NULL OR (
      jsonb_typeof(attestation) = 'object'
      AND attestation ?& ARRAY['staff_user_id', 'staff_display_name', 'statement', 'original_disposition', 'paper_signers']
      AND (attestation - 'staff_user_id' - 'staff_display_name' - 'statement' - 'original_disposition' - 'paper_signers') = '{}'::jsonb
      AND jsonb_typeof(attestation -> 'staff_user_id') = 'string'
      AND jsonb_typeof(attestation -> 'staff_display_name') = 'string'
      AND attestation ->> 'statement' = 'true_copy'
      AND attestation ->> 'original_disposition' IN ('retained', 'returned_to_signer', 'destroyed_per_policy')
      AND jsonb_typeof(attestation -> 'paper_signers') = 'array'
      AND jsonb_array_length(attestation -> 'paper_signers') >= 1
    )
  ),
  -- created -> completed_pending_seal -> sealed, plus voided before the seal. Never in_progress,
  -- declined or expired: there is nobody to sign, decline or run out of time.
  ADD CONSTRAINT envelopes_kind_status CHECK (
    kind = 'electronic' OR status IN ('created', 'completed_pending_seal', 'sealed', 'voided')
  );

COMMENT ON COLUMN envelopes.kind IS
  'electronic: signed through sessions (the base spec). paper_archive: a scan of a document signed '
  'in ink, filed and attested by the host (Addendum 1 A).';
COMMENT ON COLUMN envelopes.attestation IS
  'Paper archives only. {staff_user_id, staff_display_name, statement, original_disposition, '
  'paper_signers: [{display_name, capacity}]}. Names are PHI: cover page and certificate only.';

-- The scan is a blob and a revision of its own kind, so nothing can mistake it for a rendered
-- template. Column CHECKs written inline in 0001 carry the default <table>_<column>_check names.
ALTER TABLE blobs DROP CONSTRAINT blobs_kind_check;
ALTER TABLE blobs ADD CONSTRAINT blobs_kind_check CHECK (kind IN
  ('template_pdf', 'presented_pdf', 'revision_pdf', 'final_unsealed_pdf', 'sealed_pdf', 'signature_image',
   'scan_pdf'));

ALTER TABLE document_revisions DROP CONSTRAINT document_revisions_kind_check;
ALTER TABLE document_revisions ADD CONSTRAINT document_revisions_kind_check CHECK (kind IN
  ('presented', 'signer_applied', 'final_unsealed', 'sealed', 'scan'));

-- ================================================================ B. adopted signatures

-- One saved signature per user per host. Created only by the signer inside their own session
-- (created_by_session_id, created_in_envelope_id say which); never deleted; replaced or removed
-- by revoking. The image is a signature_image blob, write-once like every blob.
CREATE TABLE adopted_signatures (
  id                     uuid PRIMARY KEY,
  host_id                uuid NOT NULL REFERENCES hosts(id),
  host_user_id           text NOT NULL,             -- opaque host identifier, as on signers
  kind                   text NOT NULL CHECK (kind IN ('drawn', 'typed')),
  image_sha256           bytea REFERENCES blobs(sha256),
  typed_text             text,                      -- a name: DB and PDF only, never logs or audit data
  created_in_envelope_id uuid NOT NULL REFERENCES envelopes(id),
  created_by_session_id  uuid NOT NULL REFERENCES signing_sessions(id),
  created_at             timestamptz NOT NULL DEFAULT now(),
  revoked_at             timestamptz,
  revoke_reason          text CHECK (revoke_reason IN ('replaced', 'user', 'host')),
  CHECK ((kind = 'drawn') = (image_sha256 IS NOT NULL)),
  CHECK ((kind = 'typed') = (typed_text IS NOT NULL)),
  CHECK ((revoked_at IS NULL) = (revoke_reason IS NULL))
);

-- At most one live row per user per host: the lookup the session payload makes, and the rule
-- adopt_signature relies on when it revokes the old row as `replaced`.
CREATE UNIQUE INDEX adopted_signatures_one_live_per_user
  ON adopted_signatures (host_id, host_user_id)
  WHERE revoked_at IS NULL;

-- Append-only, with one exception: a live row may be revoked, once. The revocation sets exactly
-- revoked_at and revoke_reason, both at the same time, and every other column stays as it was.
-- A revoked row cannot be un-revoked, re-revoked with a different reason, or deleted.
CREATE FUNCTION adopted_signatures_guard() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF TG_OP = 'DELETE' THEN
    RAISE EXCEPTION 'DELETE on adopted_signatures is forbidden: rows are revoked, never removed';
  END IF;
  IF OLD.revoked_at IS NOT NULL THEN
    RAISE EXCEPTION 'adopted signature % is revoked and immutable', OLD.id;
  END IF;
  IF NEW.revoked_at IS NULL OR NEW.revoke_reason IS NULL THEN
    RAISE EXCEPTION 'the only permitted UPDATE on adopted_signatures sets revoked_at and revoke_reason';
  END IF;
  IF (to_jsonb(NEW) - 'revoked_at' - 'revoke_reason') <> (to_jsonb(OLD) - 'revoked_at' - 'revoke_reason') THEN
    RAISE EXCEPTION 'adopted signature % may only be revoked; no other column may change', OLD.id;
  END IF;
  RETURN NEW;
END $$;

CREATE TRIGGER adopted_signatures_guard BEFORE UPDATE OR DELETE ON adopted_signatures
  FOR EACH ROW EXECUTE FUNCTION adopted_signatures_guard();
CREATE TRIGGER adopted_signatures_no_truncate BEFORE TRUNCATE ON adopted_signatures
  FOR EACH STATEMENT EXECUTE FUNCTION forbid_mutation();

-- Grants, stated rather than inherited (0002 / 0602 default privileges would give the same, but
-- an evidence table says what it allows next to its trigger): read, insert, and the one UPDATE
-- the trigger permits. No DELETE, no TRUNCATE.
REVOKE ALL ON TABLE adopted_signatures FROM esign_app;
GRANT SELECT, INSERT, UPDATE ON TABLE adopted_signatures TO esign_app;
GRANT EXECUTE ON FUNCTION adopted_signatures_guard() TO esign_app;

-- A capture may apply a saved signature. The row then names the adopted_signatures row (whose
-- image or text is what was stamped) instead of carrying its own image or text: one place holds
-- the ink, and the trail's CaptureRef carries its digest. signature_captures is append-only
-- (0502); ADD COLUMN and a new CHECK touch no row.
ALTER TABLE signature_captures
  ADD COLUMN adopted_signature_id uuid REFERENCES adopted_signatures(id);
ALTER TABLE signature_captures DROP CONSTRAINT signature_captures_kind_check;
ALTER TABLE signature_captures
  ADD CONSTRAINT signature_captures_kind_check CHECK (kind IN ('drawn', 'typed', 'click', 'adopted')),
  ADD CONSTRAINT signature_captures_kind_adopted CHECK ((kind = 'adopted') = (adopted_signature_id IS NOT NULL));

-- ================================================================ C. re-authentication span

-- Whose attestation this is, copied from the session's signer at insert, so "the most recent
-- attestation for this user on this host" is one indexed lookup that never crosses a host.
-- reauth_attestations is append-only, so the rows written before this migration cannot be
-- backfilled: they stay NULL, and a NULL row is never borrowed by another session (it still
-- serves its own session exactly as before). Every row written from now on carries both.
ALTER TABLE reauth_attestations
  ADD COLUMN host_id uuid REFERENCES hosts(id),
  ADD COLUMN host_user_id text,
  ADD CONSTRAINT reauth_attestations_user_pair CHECK ((host_id IS NULL) = (host_user_id IS NULL));

CREATE INDEX reauth_attestations_by_user
  ON reauth_attestations (host_id, host_user_id, auth_time DESC)
  WHERE host_id IS NOT NULL;

COMMENT ON COLUMN reauth_attestations.host_id IS
  'With host_user_id: whose attestation this is, copied from the session''s signer at insert. '
  'NULL only on rows from before 0700, which no other session may borrow.';
