-- 0800: Addendum 2 (docs/SPEC-ADDENDUM-2.md). Owned by the architecture, like 0001 and 0700:
-- everything under the addendum's "Model" heading, made once so the three builders (the documents
-- work, the envelope and API work, the demo host and the end-to-end run) can build in parallel
-- against a fixed schema. Module authors do not edit this file.
--
--   envelopes.source            template (today) or host_document (the host sent the PDF)
--   envelopes.field_definitions the resolved FieldDef / SignerRoleDef lists, when there is no
--                               template version to hold them
--   document_revisions.kind     gains 'supplied': revision 1 of a host document
--   document_revisions.page_count  persisted once, so nothing re-parses a 30-page PDF to count it
--   blobs.kind                  gains 'supplied_pdf': the upload, as received, beside the revision
--
-- Conventions follow 0001 and 0700: CHECKs tie a value to the columns that only make sense with
-- it, a jsonb column that carries a contract type gets a shape CHECK beside it, and nothing here
-- touches an existing row. Grants are unchanged: no new table, and the app role's rights on
-- envelopes, blobs and document_revisions already say what they allow (SPEC section 2).

-- ================================================================ where revision 1 came from

-- An electronic envelope is either rendered from a published template version (everything the base
-- spec describes) or supplied by the host over its API key. A paper archive has neither: it carries
-- the default so the column is never NULL, and the CHECK below makes 'host_document' meaningless
-- for it rather than merely unused.
ALTER TABLE envelopes
  ADD COLUMN source text NOT NULL DEFAULT 'template'
    CONSTRAINT envelopes_source_check CHECK (source IN ('template', 'host_document')),
  -- {"fields": [FieldDef...], "signer_roles": [SignerRoleDef...]} for a host document: what a
  -- template_versions row holds for everything else. Written once, at creation, with the pages
  -- already resolved to positive numbers (contracts.resolve_page); the marks it governs are
  -- stamped into revisions whose hashes are in the trail.
  ADD COLUMN field_definitions jsonb;

ALTER TABLE envelopes
  -- 0700 tied template_version_id to the kind alone. A host-document envelope is electronic and
  -- has no template version, so the rule is now about the source as well: exactly the envelopes
  -- that say 'template' *and* are electronic name a template version, and no others.
  DROP CONSTRAINT envelopes_kind_template,
  ADD CONSTRAINT envelopes_source_template CHECK (
    (kind = 'electronic' AND source = 'template') = (template_version_id IS NOT NULL)
  ),
  -- source describes how an electronic document was produced. There is no such thing as a
  -- host-supplied paper archive: a scan arrives through POST /v1/archives with an attestation.
  ADD CONSTRAINT envelopes_source_kind CHECK (kind = 'electronic' OR source = 'template'),
  -- The definitions live on the envelope exactly when there is no template version to hold them.
  ADD CONSTRAINT envelopes_source_field_definitions CHECK (
    (source = 'host_document') = (field_definitions IS NOT NULL)
  ),
  -- Their shape: an object with exactly these two keys, both non-empty arrays. Every declared
  -- role must resolve to at least one signature field, which is validate_definitions' job and not
  -- expressible here; what is expressible is that neither list is missing, null or something
  -- other than a list.
  ADD CONSTRAINT envelopes_field_definitions_shape CHECK (
    field_definitions IS NULL OR (
      jsonb_typeof(field_definitions) = 'object'
      AND field_definitions ?& ARRAY['fields', 'signer_roles']
      AND (field_definitions - 'fields' - 'signer_roles') = '{}'::jsonb
      AND jsonb_typeof(field_definitions -> 'fields') = 'array'
      AND jsonb_array_length(field_definitions -> 'fields') >= 1
      AND jsonb_typeof(field_definitions -> 'signer_roles') = 'array'
      AND jsonb_array_length(field_definitions -> 'signer_roles') >= 1
    )
  );

COMMENT ON COLUMN envelopes.source IS
  'template: revision 1 was rendered from a published template version with the host''s prefill '
  '(the base spec). host_document: the host''s backend supplied the PDF itself (Addendum 2). '
  'Electronic envelopes only; a paper archive carries the default and means nothing by it.';
COMMENT ON COLUMN envelopes.field_definitions IS
  'Host documents only. {"fields": [FieldDef], "signer_roles": [SignerRoleDef]} -- what a '
  'template version holds for a template envelope. Pages are resolved (1-based, positive) before '
  'they are written here; a label is shown in the signing UI, so it carries no PHI.';

-- ================================================================ the document itself

-- The upload as received, before flattening. Stored beside the flattened revision 1 and hashed
-- into document.supplied, so the step from what the host sent to what the signer was shown is
-- evidence rather than an assertion. Column CHECKs written inline in 0001 carry the default
-- <table>_<column>_check names; 0700 rewrote this one already.
ALTER TABLE blobs DROP CONSTRAINT blobs_kind_check;
ALTER TABLE blobs ADD CONSTRAINT blobs_kind_check CHECK (kind IN
  ('template_pdf', 'presented_pdf', 'revision_pdf', 'final_unsealed_pdf', 'sealed_pdf', 'signature_image',
   'scan_pdf', 'supplied_pdf'));

-- Revision 1 of a host-document envelope: the hygiene-checked, flattened bytes actually presented.
-- A kind of its own, like 'scan', so nothing can mistake it for a rendered template.
ALTER TABLE document_revisions DROP CONSTRAINT document_revisions_kind_check;
ALTER TABLE document_revisions ADD CONSTRAINT document_revisions_kind_check CHECK (kind IN
  ('presented', 'signer_applied', 'final_unsealed', 'sealed', 'scan', 'supplied'));

-- How many pages this revision has, recorded once when it is written. A 30-page report is parsed
-- on every presentation and every viewed-every-page check otherwise, and the page count is asked
-- for in more places than it is expensive in. Nullable and never backfilled: document_revisions is
-- append-only (the trigger in 0001 refuses UPDATE as well as DELETE), so rows written before this
-- migration keep NULL for ever and the code falls back to counting for them. Every revision
-- written from now on carries it.
ALTER TABLE document_revisions
  ADD COLUMN page_count integer
    CONSTRAINT document_revisions_page_count_check CHECK (page_count IS NULL OR page_count >= 1);

COMMENT ON COLUMN document_revisions.page_count IS
  'Pages in this revision, recorded when it was written (Addendum 2). NULL only on rows from '
  'before 0800, which are counted the old way.';
