-- 0900: Addendum 4 (docs/SPEC-ADDENDUM-4.md). Owned by the architecture, like 0001, 0700 and 0800:
-- the schema the review-evidence, display-timezone and SDK-mode work builds against. Module
-- authors do not edit this file.
--
--   hosts.display_timezone          IANA name for dates printed under a signature; NULL uses the
--                                   process default (DEFAULT_DISPLAY_TIMEZONE)
--   signing_sessions.client_mode    iframe (today) or sdk (the host's page imports the library)
--
-- Conventions follow 0001: a CHECK ties a value to the columns that only make sense with it, and
-- nothing here touches an existing row's meaning. Grants are unchanged: no new table.

ALTER TABLE hosts
  ADD COLUMN display_timezone text
    CONSTRAINT hosts_display_timezone_check CHECK (
      display_timezone IS NULL OR (
        char_length(display_timezone) BETWEEN 1 AND 64
        AND display_timezone ~ '^[A-Za-z0-9_+\-/]+$'
      )
    );

COMMENT ON COLUMN hosts.display_timezone IS
  'IANA timezone used when a signature caption prints the signing date (Addendum 4). NULL means '
  'the process default (DEFAULT_DISPLAY_TIMEZONE). signed_at stays UTC from Clock; this is display '
  'only.';

ALTER TABLE signing_sessions
  ADD COLUMN client_mode text NOT NULL DEFAULT 'iframe'
    CONSTRAINT signing_sessions_client_mode_check CHECK (client_mode IN ('iframe', 'sdk'));

COMMENT ON COLUMN signing_sessions.client_mode IS
  'How this session is driven (Addendum 4). iframe: the service''s framed UI, as before. sdk: the '
  'host''s page imports the signing library and calls the Signer API from the signer''s browser. '
  'Chosen by the host at session creation, never by the browser.';
